package main

var idea = `

> A curated list of my GitHub stars!  Generated by [collect-repos](https://github.com/zoroqi/collect-repos), idea comes from [starred](https://github.com/maguowei/starred)  

`

var starsDesc = `# Awesome Stars [![Awesome](https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg)](https://github.com/sindresorhus/awesome)
` + idea +
	`
## Contents(%d)

`

var reposDesc = `# %s repositories
` + idea +
	`
## Contents(%d)

`

var license = `
## License

[![CC0](http://mirrors.creativecommons.org/presskit/buttons/88x31/svg/cc-zero.svg)](https://creativecommons.org/publicdomain/zero/1.0/)

To the extent possible under law, [%s](https://github.com/%s) has waived all copyright and related or neighboring rights to this work.
`

var message = `github-actions commit`